context:
  version: "0.1.8"

package:
  name: unocss-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/unocss-language-server/-/unocss-language-server-${{ version }}.tgz
  sha256: d7ac4cd7fe949b614c8f88bc51adee3fbb68d8f8915f867ca039d4c279f6df6b

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - unocss-language-server 2>&1 | grep -q 'Connection input stream is not set.'

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language server for UnoCSS
  homepage: https://github.com/xna00/unocss-language-server
  repository: https://github.com/xna00/unocss-language-server

extra:
  recipe-maintainers:
    - danielnachun
